#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon May 14 13:53:53 2018

@author: fulvio
"""
import cv2
import numpy as np
from matplotlib import pyplot as plt


def bgr_to_chR_chG(bgrImg):
    rows, cols, _ = bgrImg.shape
    
    chR = np.zeros((rows, cols), np.float)
    chG = np.zeros((rows, cols), np.uint8)
    chB = np.zeros((rows, cols), np.float)
    
    for x in range(0,rows):
        for y in range(0,cols):
            if  (bgrImg[x,y,1] != 0):
               
                r = float(bgrImg[x,y,2]) / float(255)
                g = float(bgrImg[x,y,1]) / float(255)
                b = float(bgrImg[x,y,0]) / float(255)
                
                # r chromaticity componen
                chR[x,y] = np.uint8(r*255 / (r+g+b))
                
                #g chromaticity component
                chG[x,y] = np.uint8(g*255 / (r+g+b))
                
                chB[x,y] = np.uint8(b*255 / (r+g+b))
                
    return chR, chB, chG


img = cv2.imread('RGB_29.png')

chR, chB, chG = bgr_to_chR_chG(img)

kernel = np.ones((5,5),np.float32)/25
dst = cv2.filter2D(chG,-1,kernel)
#
#chG = cv2.equalizeHist(dst)

print("max chG: ", np.amax(chG), "min chG: ", np.amin(chG))

laplacian = cv2.Laplacian(chG,cv2.CV_64F)
sobelx = cv2.Sobel(chG,cv2.CV_64F,1,0,ksize=5)
sobely = cv2.Sobel(chG,cv2.CV_64F,0,1,ksize=5)

plt.figure()
plt.hist(chG.ravel(),256,[0,256])
plt.title("histogram chG")

rows, cols = chG.shape

for x in range(0,rows):
        for y in range(0,cols):
            if(chG[x,y] < 73 or chG[x,y] > 79):
                chG[x,y] = 0
            else:
                chG[x,y] = 255
                    
                
                


plt.subplot(2,2,1),plt.imshow(chG,cmap = 'gray')
plt.title('only minimum and maximum'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,2),plt.imshow(laplacian,cmap = 'gray')
plt.title('Laplacian'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,3),plt.imshow(sobelx,cmap = 'gray')
plt.title('Sobel X'), plt.xticks([]), plt.yticks([])
plt.subplot(2,2,4),plt.imshow(sobely,cmap = 'gray')
plt.title('Sobel Y'), plt.xticks([]), plt.yticks([])

plt.show()

